0xSpaceShard/starknet-hardhat-plugin

Dockerfile
README.md
package.json
src/constants.ts
src/index.ts
src/type-extensions.ts

- Allow user to specify the docker image used (e.g. `0.4.0` or `latest`).
- Edit dockerfile to require ARG CAIRO_VERSION.
- Add an npm task for building docker images (requires an env var): `CAIRO_VERSION=0.4.1 npm run build-image`
- Allow user to specify sources path (defaults to `contracts`, same as default for solidity).

Read image and sources from config

---

README.md
src/index.ts
src/types.ts

- Allow importing custom files; fix #12
- Allow specifying library paths on the command line (new CLI parameter `--cairo-path`).
- Trim whitespace on function call output end.

Fix compile path

---

src/types.ts

- When deploying in mocha tests, the deployment process wasn't waited to turn from RECEIVED to PENDING.
- This was solved by reusing the existing `iterativelyCheckStatus` function. Since it was a method of `StarknetContract`, and deployment is done in `StarknetContractFactory`, the function was moved outside and the code was adapted to be used within both classes.
- Some minor refactoring was done to improve code readability. Existing regex extraction code was organized into:
- `extractFromResponse`, `extractTxHash` and `extractAddress`
- Now checking for the possibility of REJECTED in the process of iteratively checking the tx status after deploy/invoke

Wait for deployment to be pending; check for tx rejection

---

README.md
src/constants.ts
src/index.ts
src/starknet-wrappers.ts
src/types.ts

- Fix path documentation for `starknet-verify`.
- Support different mainnet namings (so far only `alphaMainnet` was supported, now `alpha-mainnet` is also).
- Refactor `StarknetWrapper.runCommand` to: `compile`, `deploy`, `getTxStatus`, `invokeOrCall`.
- Make the macOS localhost adaptations only in `DockerWrapper`:
- Interacting with `starknet-devnet` on macOS using `venv` is now fixed (@octate please approve this PR if you find this to be true).
- Closes #27

Refactor running Starknet commands; Fix devnet interaction on macOS+venv

---

README.md
scripts/test.sh
src/constants.ts
src/starknet-wrappers.ts
src/task-actions.ts

- Changed how status messages are logged in"processExecuted".
- Added "await" to all promise returns that didn't have it in StarknetWrapper.
- Increased status check timeout to 2 seconds.
- Updated README.
- Changed testing so that alpha network is only tested on linux machines in CircleCI.

Deploy logging and consistent await

---

src/adapt.ts
test/general-tests/function-argument-number/check.sh
test/general-tests/function-argument-number/hardhat.config.ts

Considering the cairo function:
﻿```func foo(a: felt) -> (res: felt):
﻿end```﻿
The following testing code samples with incorrect number of arguments should fail
```
contract.call("foo", { a: 1, b: 2 });
contract.call("foo"); 
```
In functions that take arrays as arguments, the array length is not considered as an argument.

Added check for number of arguments and nested objects' members

---

.circleci/config.yml
.eslintrc.json
README.md
hardhat.config.ts
package-lock.json
package.json
src/adapt.ts
src/extend-utils.ts
src/index.ts
src/starknet-types.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/type-extensions.ts
src/types.ts
src/utils.ts
test/general-tests/short-string-test/short-string-test.ts

- This PR introduces no changes to the way users will use the plugin.
- Support linting and formatting (ESLint):
- Rules are defined in `.eslintrc.json`
- Make changes to remove the errors reported by the linter.
- Add linting to CI.
- `stringToBigInt` was the only function requiring refactor. I did it because linter was complaining about the `\x00` used in the regex.
- Update Readme with `require` counterparts of `import` statements.
Yes, yes, should've been added long ago.

Add linting; Update Readme with `require` statements

---

src/adapt.ts

StarkNet calls will return negative numbers (ex. `-0x001`) but `BigInt` can't parse negative hexadecimal strings (`BigInt("-0x001")` will fail with `Cannot convert -0x001 to a BigInt`). `BigInt` will happily parse both `-0x001` (not as a string) and `"0x001"` (positive value as a string).
This change simply strips the sign off, converts the (now positive) hexadecimal value to `BigInt` and negates before returning.

Parse negative hexadecimal outputs to BigInt

---

.eslintrc.json
src/adapt.ts
src/starknet-wrappers.ts

- This PR contains no usage changes.
- Enforce `@typescript/no-unused-vars`, `semi-spacing`, `block-spacing` to raise errors in the linting process.

Update linter (no-unused-vars, semi-spacing, block-spacing)

---

README.md
src/index.ts
src/task-actions.ts
src/type-extensions.ts
src/types.ts

- Multiple paths are allowed now for `hardhat.config` file.
- Error message from a rejected transaction now displayed.

Multiple sources paths, rejected transaction error message

---

src/constants.ts
src/types.ts

Fix UnhandledPromise error caused by checking the transaction status;
When transaction status check fails, the call is retried.

Fixed UnhandledPromise error, retry check status on 503

---

src/starknet-wrappers.ts

- Users will now be able to provide venv paths (in hardhat.config) which contain a tilde:
- Such interpretation of tilde is actually bash-specific, but I think this would bring more benefit than risk.
- Switched a `let` variable to a `const` in the same function where the homedir resolution is done.

Expand tilde to homedir in venv path

---

README.md
src/extend-utils.ts
src/index.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/type-extensions.ts
src/types.ts
test/configuration-tests/with-artifacts-path/hardhat.config.ts
test/configuration-tests/with-cairo-version/hardhat.config.ts
test/configuration-tests/with-cli-paths/hardhat.config.ts
test/configuration-tests/with-deploy-inputs/hardhat.config.ts
test/configuration-tests/with-deploy-path/hardhat.config.ts
test/configuration-tests/with-networks/hardhat.config.ts
test/configuration-tests/with-networks/invalid-mocha-network.txt
test/configuration-tests/with-sources-path/hardhat.config.ts
test/configuration-tests/with-wait/hardhat.config.ts
test/general-tests/function-argument-number/hardhat.config.ts
test/general-tests/open-zeppelin-cairo-contracts/hardhat.config.ts
test/general-tests/plain/hardhat.config.ts
test/general-tests/short-string-test/short-string-test.ts
test/general-tests/starknet-call/hardhat.config.ts
test/general-tests/starknet-invoke/hardhat.config.ts
test/general-tests/starknet-verify/hardhat.config.ts
test/general-tests/transaction-signing/hardhat.config.ts
test/general-tests/wallet-test/hardhat.config.ts
test/venv-tests/with-venv-active/hardhat.config.ts
test/venv-tests/with-venv/hardhat.config.ts

- Rename string to shortString:
- `stringToBigInt` -> `shortStringToBigInt`
- `bigIntToString` -> `bigIntToShortString`
- Restructure `hardhat.config`:
- Use `starknet` key.
- Stop using `cairo` key:
- Rename `version` to `dockerizedVersion`
- Move `wallets` to `starknet`.
- Move `starknetNetwork` from `mocha` to `starknet`.
- Use `options` object in `StarknetContract` methods instead of using optional function arguments.
- Add Docker issue fix to Readme.
- No dev-specific changes to list.

Introduce breaking changes for 0.4.0

---

scripts/install-devnet.sh

- No changes to how the plugin is used.
- Fix poetry version to 1.1.12 because using the latest (1.1.13 currently) is not working. @dribeiro-ShardLabs does this have to do anything with caching? Perhaps if venv was cached?
- Also changed the formatting of `install-devnet.sh`.

Fix poetry to version 1.1.12

---

src/devnet-utils.ts

- Provide updated typing of flush response. Kept snake_case because it's only meant for logging/debugging.
- None

Reflect flush resp with l1 and l2 messages

---

.eslintrc.json
src/account.ts
src/adapt.ts
src/types.ts

- Allow passing `BigNumber` and `Array` arguments through Account
- Refactore code:
- Expose `adaptInput` and `adaptOutput` on `StarknetContract` - this can be reverted

Account adapt input

---

package-lock.json
package.json

- Update hardhat dependency to version 2.9.0 (with updated mocha)
- Will properly fail for non-matching BigInt values in tests.

Update hardhat to 2.9.0

---

src/index.ts
src/task-actions.ts
test/general-tests/starknet-verify/check.sh

Adapt the contract verification to be compatible with the new Voyager update

Updated starknet-verify action

---

.circleci/config.yml
src/account-utils.ts
src/account.ts
src/constants.ts
src/extend-utils.ts
src/index.ts
src/type-extensions.ts
test/general-tests/account-test/check.sh

Fetching the artifacts for the account contract automatically, so the contract name parameter is removed from the functions `deployFromABI` and `getAccountFromAddress`

Automatic account artifacts fetching

---

src/adapt.ts
src/types.ts
test/general-tests/constructor-test/check.sh
test/general-tests/constructor-test/hardhat.config.ts
test/general-tests/constructor-test/network.json

- Support contracts with empty constructors (constructors with no arguments).
- `handleConstructorArguments` is simplified
- Constructor behavior is tested in a separate test (only on devnet).

Fix empty constructor

---

README.md
src/devnet-utils.ts
src/extend-utils.ts
src/index.ts
src/type-extensions.ts

- Change name of the account deploying function to reflect its purpose.
- Update Readme.
None

Rename deployAccountFromABI to deployAccount

---

src/account-utils.ts
src/account.ts
src/types.ts
test/general-tests/account-test/check.sh

- Users no longer need to explicitly create a `starknet-artifacts/account-contract-artifacts` folder to avoid the error `Error: ENOENT: no such file or directory`
- Check if the account artifacts exist before accessing the folder;
- Account invoke() return is of type `type InvokeResponse = string`, and it returns the transaction hash of the invoke.

Hotfix for account artifacts, return tx hash on invoke

---

.circleci/config.yml
scripts/ensure-python.sh
scripts/install-devnet.sh
scripts/test.sh

None
- In CircleCI, Use Python 3.8.9 with pyenv (previously used the default Python3 (3.9))

Use pyenv in CircleCI

---

.circleci/config.yml
README.md
src/account-utils.ts
src/account.ts
src/adapt.ts
src/constants.ts
src/index.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/types.ts
test/configuration-tests/with-cairo-version/hardhat.config.ts
test/general-tests/starknet-call/no-inputs.txt
test/general-tests/starknet-call/too-few-inputs.txt
test/general-tests/starknet-call/too-many-inputs.txt
test/general-tests/starknet-estimate-fee/check.sh
test/general-tests/starknet-estimate-fee/hardhat.config.ts
test/general-tests/starknet-estimate-fee/no-inputs.txt
test/general-tests/starknet-estimate-fee/too-few-inputs.txt
test/general-tests/starknet-estimate-fee/too-many-inputs.txt
test/general-tests/starknet-invoke/no-inputs.txt
test/general-tests/starknet-invoke/too-few-inputs.txt
test/general-tests/starknet-invoke/too-many-inputs.txt

- Introduce `hardhat starknet-estimate-fee`.
- Introduce `StarknetContract.estimateFee`.
- Use `0.8.0` docker version by default`.
- Support hex strings as contract function input.
- Make `Choice` more refined:
- Distinguish between:
- `ExecuteChoice = "invoke" | "call"`
- `InteractChoice = ExecuteChoice | estimate_fee`
- Rationale:
- `estimate_fee` can reuse a lot of old code

Adapt to 0.8.0

---

README.md
src/devnet-utils.ts
src/extend-utils.ts
src/index.ts
src/starknet-types.ts
src/starknet-wrappers.ts
src/type-extensions.ts
src/types.ts
test/general-tests/starknet-estimate-fee/no-inputs.txt
test/general-tests/starknet-estimate-fee/too-few-inputs.txt
test/general-tests/starknet-estimate-fee/too-many-inputs.txt

-  Implement `getTransaction` and `getTransactionReceipt` functions for the `starknet` object
- `GetTxStatusWrapperOptions` type was changed to a more generic `TxHashQueryWrapperOptions`, because there are now multiple functions that use the same structure for transaction hash based queries:
-- `prepareGetTxStatusOptions` was changed to `prepareGetTxQueryOptions`, and now takes an additional argument `command` as a parameter;
- `L1Message` and `L2Message` types were changed to `L1ToL2Message` and `L2ToL1Message` respectively to be more clear;

Added getTransaction and getTransaction receipt functions

---

README.md
src/account-utils.ts
src/account.ts
src/constants.ts
src/extend-utils.ts
src/index.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/type-extensions.ts
src/types.ts
src/utils.ts
test/configuration-tests/with-compilation-options/check.sh
test/configuration-tests/with-compilation-options/contract_with_execute.cairo
test/configuration-tests/with-compilation-options/hardhat.config.ts
test/configuration-tests/with-compilation-options/without-account-flag.txt
test/general-tests/wallet-test/network.json
tsconfig.json

- Allow specifying maxFee and nonce.
- Introduce `--account-contract` flag for compiling account contracts.
- Account contracts are currently those with a function called `__execute__`, hence the addition of such a test. Couldn't make it 
- Enable wallet testing on devnet.
- Revert to es2016 in tsconfig.json (es2020 was never a part of an official plugin release, but happened in a commit between the latest release and this commit).
- Introduce `copyWithBigint` which basically takes an already existing functionality and wraps it into a function. The function is now used in one more place.
- Make Account methods protected.
- Unfortunately some hackiness is introduced in multiInteract in account.ts, if the reviewer should find a better way of dealing with it
- Refactor InteractChoice making …

Invoke options

---

scripts/assert-contains.py
test/configuration-tests/with-compilation-options/check.sh
test/configuration-tests/with-compilation-options/without-account-flag.txt

None
- Introduce a Python script for asserting that an input stream contains a pattern.
- Remove the file holding the expected content.

Add assert-contains.py script

---

test/configuration-tests/with-account-compilation-option/check.sh
test/configuration-tests/with-disable-hint-compilation-option/check.sh

None
- Fix of https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/85
- Fix paths in compilation-option tests
- Cancelled the workflow because it had already run successfully prior to rebasing: [CircleCI link](https://app.circleci.com/pipelines/github/Shard-Labs/starknet-hardhat-plugin/810/workflows/067fc481-af83-43a6-86f4-5d1a930f474f)

Fix paths in compilation-option tests

---

README.md
src/index.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/types.ts

- Introduce `--token` flag for whitelisted deployment
- Remove defaulting to `undefined` with ternary in task-actions.ts

Introduce --token flag for whitelisted deployment

---

README.md
scripts/get-version.py
src/account.ts
src/types.ts
test/general-tests/account-test/network.json

- No need for passing `transactionVersion` as a part of fee estimation options.
- Bring back account testing on devnet.
- Use starknet-devnet v0.1.23 for testing.
- Set EstimateFeeOptions to be the same as CallOptions again.

Enable normal fee estimation on Devnet

---

package-lock.json
package.json
src/constants.ts
src/index.ts
src/task-actions.ts
src/type-extensions.ts
src/utils.ts
src/verification.ts
test/general-tests/starknet-verify/check.sh
test/general-tests/starknet-verify/network.json

- Adapt `starknet-verify` to the new Voyager API.
- Since Voyager almost always returns 502 Bad Gateway, it was hard to do some meaningful error interpretation. That's why in case of an unsuccessful verification the most likely reasons are listed.
- Modify and uncomment verification testing.

Adapt Voyager verification

---

README.md
src/account-utils.ts
src/account.ts
src/extend-utils.ts
src/index.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/type-extensions.ts
src/types.ts
src/utils.ts
test/general-tests/starknet-verify/check.sh

- Add deployment options to deployAccount (salt, token, privateKey).
- Stop masking error on contract deployment:
- So far all deployment errors were masked by `Could not deploy contract. Check the network url in config. Is it responsive?`
- Now the actual error is printed (will be somewhat messier, but more informative).
- Fix formatting.
- Fix Voyager test and increase the sleep time done in it.
- Fix checking for integrated devnet

Add deployment options to deployAccount

---

src/type-extensions.ts
test/configuration-tests/with-networks/hardhat.config.ts

- Fix issue with `hardhat` network being configured in hardhat.config.ts
- Make `url` an **optional** property of `HardhatNetworkUserConfig`.
- Introduce hardhat network entry to hardhat.config.ts used in the network configuration test.

Make url optional for hardhat network config

---

README.md
src/account.ts

- Until now users had to do `account.starknetContract.address`, but now they could just do `account.address`
- Added address getter for `account.starknetContract.address` to Account class

Added getter for starknetContract.address in Account class

---

config.json
package-lock.json
package.json

- Release v0.5.5
- Make integrated-devnet use devnet v0.2.2 by default
- Use devnet v0.2.2 for testing

Release v0.5.5

---

README.md
src/devnet-utils.ts
src/type-extensions.ts

- Block timestamp can be handled using the two devnet functions `increaseTime()` and `setTime()`
- `setTime()` wil update the subsequent block timestamp keeping the offset

Time manipulation functions

---

README.md
src/index.ts
src/task-actions.ts
test/general-tests/starknet-verify/check.sh

- Plugin now supports contract verification on multiple directory levels.
- Additionally, the verifier accepts
- More details on [readme](https://github.com/Shard-Labs/starknet-hardhat-plugin/tree/voyager#starknet-verify).
```
- Compiler Version
- License scheme
- Contract Name (optional)
- Account Contract (optional)
```
- `filename` changed to `filepath` when appending to the payload using `FormData`

Adapt to new Voyager verification API

---

scripts/test.sh
src/adapt.ts
src/extend-utils.ts
src/index.ts

- Added support for type aliases and named tuples
- Fixed issue with nested tuples
- Closes https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/103
-

Support named tuples, nested tuples and type aliases

---

README.md
scripts/test.sh
src/devnet-utils.ts
src/type-extensions.ts
test/general-tests/devnet-dump-and-load/check.sh
test/general-tests/devnet-dump-and-load/hardhat.config.ts
test/general-tests/devnet-dump-and-load/network.json

-  Support for `/dump` and `/load` devnet endpoints.
- None
-   [x] No linter errors
-   [x] Tried to avoid introducing linter warnings
-   [x] Updated the `test` directory
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example/pull/69):
-   [x] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [x] All tests are passing

Support dump and load endpoints

---

src/devnet/integrated-devnet.ts

-   Users don't need to change anything, they will just receive better error messages if integrated-devnet fails suddenly
-   It should not affect CI/CD
-   [ ] Formatted the code
-   [ ] No linter errors
-   [ ] Tried to avoid introducing linter warnings
-   [ ] Performed a self-review of the code
-   [ ] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Updated the `test` directory
-   [ ] All tests are passing

fix: add error checks for integrated devnet process

---

README.md
src/adapt.ts
src/starknet-types.ts
src/types.ts
src/utils.ts

- Closes #136:
- This stems from multiple sources, just one is log-and-throw done in the plugin, the rest comes from the way Starknet CLI handles errors (this was addressed in a hacky way, by pattern matching) 
- Improve error logging if wrong type provided as function input
- Update docs with `getPredeployedAccounts` usage.
- Improve formatting of error messages (unescape escaped newlines)
- Refactor event decoding:
- incorporate `adaptEvent` into `decodeEvents`
- introduce type `EventAbi`
-   [x] No linter errors
-   [x] Tried to avoid introducing linter warnings
-   [x] Linked issues which this PR …

Fix logging

---

README.md
config.json
scripts/test.sh
src/account.ts
src/index.ts
src/starknet-types.ts
src/starknet-wrappers.ts
src/types.ts

- Updated estimateFee response, but without changing `amount` to `overall_fee`, just added the new properties (`gas_price`, `gas_usage`) - keeping them snake case to be in sync with other responses coming from the sequencer API.
- Updated Block structure (`starknet_version`).
- Passing `--no_wallet` to Starknet CLI where necessary.
- Tests failing until proper devnet release is done.
- Close https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/154
- Moved appropriate types to `starknet-types.ts`
-   [x] No linter errors
-   [x] Tried to avoid introducing linter warnings
-   [x] Updated the `test` …

Adapt to cairo-lang/starknet 0.9.1

---

README-dev.md
package-lock.json
package.json
src/devnet/create-devnet-wrapper.ts
src/devnet/docker-devnet.ts
src/devnet/external-server.ts
src/devnet/index.ts
src/devnet/venv-devnet.ts
src/index.ts
src/starknet-venv-proxy.ts
src/starknet-wrappers.ts
src/starknet_cli_wrapper.py

- Should only present a speed-up; no change in functionality.
- Spawn a server that acts as an intermediary between user requests and Starknet CLI
- `VenvWrapper` is modified to not spawn subprocesses (for most commands)
- Create a new abstract class `ExternalServer` which abstracts the previous `IntegratedDevnet` and the new `StarknetVenvProxy`.
- Something similar can be done for `DockerWrapper`. but in a separate PR (might include changing the cairo-cli docker image so that it includes the proxy server script).
- Not using `"python"` command directly in `VenvWrapper`, it is adapted in the constructor according to what the user specified as `venv` (`active` or not)
- Now using proprety `pythonPath`
- Currently available on npm (`@sharlabs/starknet-hardhat-plugin`) and in …

Use proxy server in VenvWrapper

---

src/devnet-utils.ts
src/devnet/integrated-devnet.ts

-   If underlying server dies, the timeouts will make sure the plugin does not freeze
-   It checks correctly until dump file has finished writing, otherwise immediate load would cause everything to explode
Resolves #167 
-   
-   [x] No linter errors
-   [x] Tried to avoid introducing linter warnings
-   < …

state: add dump/load timeout and wait until dump has finished

---

package.json
src/extend-utils.ts
src/recompiler.ts
src/task-actions.ts

- Add check to getBlockUtil (the case when an object of type `any` is passed is not properly handled - defaulting to `"latest"` is done, which might be unwanted behavior if user passes number 2 (instead of passing as a property if the identifier object).
- Add formatting script: `npm run format` (runs prettier and applies changes)
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [ ] Created a PR to the `plugin` branch …

Add check to getBlockUtil

---

src/starknet-wrappers.ts
src/starknet_cli_wrapper.py

- Should only present speedup. Similar to #175, but applied to `starknet-deploy-account` and `starknet-compile`.
- In venv mode, no more Starknet CLI commands remain accessed directly (all are accessed through the proxy server)

venv mode: do everything through proxy server

---

README.md
src/index.ts
test/configuration-tests/with-cli-network/check.sh
test/general-tests/hardhat-run/check.sh
test/general-tests/hardhat-run/hardhat.config.ts

-   `--starknet-network` can be passed to `npx hardhat run` command
-  Closes https://github.com/Shard-Labs/starknet-hardhat-plugin/issues/162
-   NA
-   [ ] …

Add optional CLI param on hardhat run

---

src/starknet-wrappers.ts

- Fix #189 
- Use python3 instead of python when spawning subprocesses.

Replace python with python3

---

README.md
scripts/test.sh
src/types.ts
test/general-tests/proxy-call/check.sh
test/general-tests/proxy-call/hardhat.config.ts
test/general-tests/proxy-call/network.json

-   Custom `abi` and `abiPath` can be set using `setAbi()` method.
-   Closes #151 
-   NA
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):https://github.com/Shard-Labs/starknet-hardhat-example/pull/75
-   [x] Restored `test.sh` to to …

Add method to set custom implementation to contracts

---

README.md
src/index.ts
src/task-actions.ts
test/general-tests/starknet-verify/check.sh

-   Changes `--account-contract` optional param to a flag in `starknet-verify` cli.
-   Closes #173 
-   NA
-   [ ] Restored `test.sh` to to use the original …

Make account-contract a flag in starknet-verify

---

README.md
src/external-server/external-server.ts
src/starknet_cli_wrapper.py

- Close #195
- In case of abnormal external server exit, always log the last error from the subprocess.
- Updated docs with config-related information (python3, docker, mac).
- Add try-except to `starknet_cli_wrapper.py` (proxy server).
- Expand error message thrown by external server in case of failure.

Handle environment without starknet in proxy server

---

src/external-server/docker-devnet.ts
src/external-server/docker-server.ts
src/starknet-docker-proxy.ts

-   Removes network mode from docker args and uses port mapping in place for arm64 machine.
-   Closes #209 
-   NA
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [ ] Restored `test.sh` to to use the …

Fix Docker Connection Timed out

---

scripts/test.sh
src/external-server/external-server.ts
src/starknet_cli_wrapper.py
test/configuration-tests/with-account-compilation-option/network.json
test/configuration-tests/with-disable-hint-compilation-option/network.json
test/general-tests/expect-error-on-compile/check.sh
test/general-tests/expect-error-on-compile/hardhat.config.ts
test/general-tests/expect-error-on-compile/invalid_contract.cairo
test/general-tests/expect-error-on-compile/network.json

- Close #207 
- Use custom error where not already present (one place had HardhatPluginError used instead of StarknetPluginError due to simultaneous development on two branches)
- Add a test which asserts compilation error content.
- Add two missing network.json files and made network.json a compulsory part of each test case (through a check in test.sh).
- Format test.sh
-   [x] All tests are passing (for …

Fix missing compilation error

---

README.md
src/types.ts

-   Changes return type of `StarknetContract.decodeEvents`
-   Closes #165 
-   NA
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
-   https://github.com/Shard-Labs/starknet-hardhat-example/pull/78
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [x] All tests are passing (for external contributors who don't have access to the CI/CD …

Change return type of function decodeEvents

---

README.md
src/constants.ts
src/index.ts
src/starknet_cli_legacy.py
src/type-extensions.ts
src/utils.ts
test/configuration-tests/with-cli-network/hardhat.config.ts
test/configuration-tests/with-networks/check.ts
test/configuration-tests/with-networks/invalid-cli-network.txt
test/configuration-tests/with-networks/invalid-config-network.txt
test/general-tests/account-test/network.json
test/general-tests/declare-test/network.json
test/general-tests/plain/network.json
test/general-tests/starknet-verify/check.ts
test/general-tests/starknet-verify/network.json
test/network.schema
test/venv-tests/with-venv-active/network.json
test/venv-tests/with-venv/network.json

- Closes #247 
- Network for Testnet 2 can be specified as `alpha-goeli2` or `alpha2`
- NA

Add predefined network for Testnet 2

---

scripts/test.sh
src/types.ts
test/configuration-tests/with-networks/check.ts
test/general-tests/cairo-migrate/check.ts
test/general-tests/starknet-call/check.ts
test/general-tests/starknet-verify/check.ts
test/integrated-devnet-tests/with-stderr-to-STDERR/check.ts
test/utils/cli-functions.ts
test/utils/deploy-funded-account.ts

- Avoids 0 passing tests message by mocha
- Removes flag for account-contract from `starknet-verify` test
- Update exec function to break on exit with status code different from 0
-   NA
-   Tests are launched by `node` instead of `mocha`
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

Use node to run tests

---

src/constants.ts
src/index.ts
src/starknet_cli_legacy.py
src/type-extensions.ts
src/utils.ts

-   Closes #263 
-   Adds new `enum` with new chain ID added for alpha goerli2
-   `"alpha-goerli2": StarknetChainId.TESTNET.value,` on `starknet_cli_legacy.py` Should be changed to `StarknetChainId.TESTNET2.value` when adapting 0.10.3.
-   NA
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

Support new chain ID for Alpha Goerli 2

---

src/constants.ts
src/devnet-utils.ts
src/external-server/external-server.ts

-   Adds timeout to requests in `devnet-utils.ts` and `externatl-server.ts`
-   Have 30 seconds as a request timeout (so far, the default axios was 0)
-   Closes #167 
-   NA

 Add timeout to devnet & integrated-devnet requests

---

src/starknet-wrappers.ts
test/venv-tests/with-venv-active/check.ts
test/venv-tests/with-venv-active/hardhat.config.ts
test/venv-tests/with-venv/check.ts
test/venv-tests/with-venv/hardhat.config.ts

- Fix `ClientConnectorError` appearing on mac with `venv` set in hardhat.config.ts
- Close #275
- Expand venv testing to include network tests
- Had we had such tests, we would have spotted this URL adaptation issue
- This used to be done but I unknowingly removed it in #256
- Close #276 
-   [x] All tests are passing (for external contributors who don't have access to the …

Fix and refactor Starknet Wrapper

---

tsconfig.json

This only limits the scole of lookup for `@types` to current directory's `node_modules`.
This only limits the scole of lookup for `@types` to current directory's `node_modules`.
-   [ ] If `src/type-extensions.ts` was changed, updated the line number referencing this file in the `## API` section of README.md
-   [ ] Created a PR to the `plugin` branch of …

#287 TypeRoots - only from this dir

---

www/docs/intro.md

-   [ ] Formatted the code
-   [ ] No linter errors + tried to avoid introducing linter warnings
-   [ ] If `src/type-extensions.ts` was changed, updated the line number referencing this file in the `## API` section of README.md
-   [ ] Restored `test.sh` …

#200 Debugging contracts

---

.eslintrc.json
.github/pull_request_template.md
src/type-extensions.ts
src/types/devnet.ts
src/types/index.ts
src/types/starknet.ts
www/docs/dev.md
www/docs/intro.md

None
- Close #286 Moved `Starknet` and `Devnet` interface definitions to dedicated files.
This makes it easier to refer the users to the interface for up to date lookup of available properties.
-  [ ] ~~If `src/type-extensions.ts` was changed, updated the line number referencing this file in the `## API` section of README.md~~ ⚠️ **Won't need this ever again** 🥳 
-   [ ] …

286 type defs

---

config.json
scripts/setup-venv.sh
scripts/test.sh
src/devnet-utils.ts
src/types/devnet.ts
www/docs/intro.md

-   Adds L1 to L2 mock endpoint on devnet `sendMessageToL1()` and `sendMessageToL2()`
-   Closes #292 
-   Fixes the issue ERROR: `Failed building wheel for fastecdsa` on `venv-test` for macos.
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):https://github.com/Shard-Labs/starknet-hardhat-example/pull/88
-   [x] Restored `test.sh` to to use the original …

Support L1-L2 mock messaging

---

test/general-tests/account-test/hardhat.config.ts
test/general-tests/contract-test/check.ts
test/general-tests/contract-test/hardhat.config.ts
test/general-tests/contract-test/network.json

Fixes #273
None
Additional tests added for `StarknetContract` and `StarknetContractFactory`.
Returns `{Promise<PredeployedAccount>}`  details of a pre-deployed account.
Returns `{Promise<OpenZeppelinAccount>}` An OZAccount instance for a pre-deployed account.
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hard …

Contract tests

---

scripts/test.sh
src/account-utils.ts
src/account.ts
src/types/index.ts
www/docs/intro.md

-   The `estimateDeployAccountFee()` function can be used to obtain the account deployment fee.
-   Closes #298 
-   NA
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):https://github.com/Shard-Labs/starknet-hardhat-example/pull/96
- …

Estimate deploy account fee

---

www/docs/dev.md
www/docs/intro.md

Fix: typos

---

src/external-server/external-server.ts

-   Closes #299 
-   NA
-   [ ] All tests are passing (for …

Expand error message with reason

---

README.md
src/constants.ts
test/configuration-tests/with-disable-hint-compilation-option/check.ts
test/configuration-tests/with-disable-hint-compilation-option/contract_with_unwhitelisted_hints.cairo
test/general-tests/cairo-migrate/check.ts
test/general-tests/cairo-migrate/old_contract.cairo
test/recompilation-tests/hardhat-test/contract_test_cache.cairo
test/recompilation-tests/hardhat-test/contract_test_cache_no_dependency.cairo
www/docs/intro.md
www/docusaurus.config.js
www/src/pages/index.js

Change "StarkNet" to "Starknet"
Close #316

fix: replace StarkNet by Starknet [skip ci] [skip-testnet]

---

src/account.ts
src/starknet-wrappers.ts
src/types/index.ts

This PR fixes the following error when passing a custom nonce to a declare transaction via the `Account` class:
```
Signature (..., ...), is invalid, with respect to the public key ..., and the message hash ...
```
This would occur because the message hash with the custom nonce would be signed, while the transaction would be created with the current account nonce. This issue made it nearly impossible to submit multiple declare transactions at the same time.
-   [X] Formatted the code
-   [X] No linter errors + tried to avoid introducing linter warnings
-   [X] Performed a self-review of the code
-   [X] Rebased to the last commit of the target branch (or merged it into my branch)
-   [X] Documented the changes
-   [ ] Updated the `test` directory (with a test case consisting of …

Pass Declare Nonce to Starknet CLI

---

scripts/test.sh
src/account.ts
src/types/index.ts
www/docs/intro.md

-  `declare()` now returns the tx instead of the class hash
- Now, the user needs to check the tx status for validating a successful declaration
- Closes #313 (breaking)
-   N/A
-   [x] Linked issues which this PR resolves (#313)
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
- …

Declare return tx hash

---

scripts/devnet-run.sh
scripts/setup-venv.sh
scripts/test-dev.sh
scripts/test-setup.sh

- A bit of formatting and UX improvement to the shell scripts used by the `npm run test-dev` script.

Polish test-dev script

---

src/utils.ts

constructors aren't found correctly if a comment exists before it.

utils.ts: fix finding constructors when a comment exists

---

src/utils.ts

when a function name is contained in any part of the constructor parameter name, it is incorrectly selected as the constructor, eg:
```
#[constructor]
fn constructor(first_owner: ContractAddress) {
...
}
#[view]
fn owner() -> ContractAddress {
_owner::read()
}
```
there is then an ABI map entry with key `owner` that ends up getting matched to the `owner` substring of `first_owner`, which causes it to get selected as the constructorAbi in the [`StarknetContractFactory` constructor](https://github.com/Shard-Labs/starknet-hardhat-plugin/blob/06bc12605eee505779a6a52385ac0ae816d32077/src/types/index.ts#L375) if it is encountered before the real constructor.
this replaces the `includes()` check with a regexp that should only match function names.

utils.ts: dont match parameters in constructor name check

---

src/starknet-wrappers.ts
src/types/index.ts

passing a cairo 1.0 abi to `starknet call` invocations result in a parser error as it's not supported, eg
```
Error: ParserError: :1:5: Unexpected token Token('COLON', ':'). Expected one of: "*", ".", end of input.
core::felt252
```
omit the abi parameter for cairo 1.0 abi's.
- Closes #347 
-   [ ] Created a PR to the `plugin` branch of …

types/index.ts: dont pass abi path for cairo 1.0 contract calls

---

src/adapt.ts
src/constants.ts
src/starknet-types.ts
src/types/index.ts
www/docs/intro.md

- support core::array::Array input and output (no support for nested - noted in docs)
- support core::bool input and output
- handle unnamed cairo 1.0 outputs
-   [ ] Modified `test.sh` to use my example repo …

cairo 1.0 input and output handling improvements

---

src/adapt.ts

should be `u32` instead of `u38`
-   [ ] All tests are …

adapt.ts: fix core::integer::u32

---

src/starknet-types.ts
src/types/index.ts

cairo 1.0 events in the ABI have arguments listed under `inputs` instead of `data`: https://github.com/starkware-libs/cairo/blob/05867c82de42d5ee5cfa953dcca1cb826402f74b/crates/cairo-lang-starknet/src/abi_test.rs#L155
-   < EXAMPLE_REPO_PR_URL …

fix reading cairo 1.0 input specs

---

src/adapt.ts

Fixes handling for core::integer::u256, which should be represented as 2 felts.
Partly addresses #341 
-   [ ] Restored `test.sh` to to use the original …

adapt.ts: add support for core::integer::u256

---

src/adapt.ts

-   Adds support for calling/invoking contracts that have type core::starknet::class_hash::ClasHash in abi of function. It is a pedersen hash just like ContractAddress so they should be parsed similarly.
None
-   [ …

Add support for class_hash::ClassHash

---

scripts/test-setup.sh
src/account-utils.ts
src/account.ts
src/starknet-wrappers.ts
src/starknet_cli_wrapper.py

- NA
-  Adds new private function, `estimateDeclareV2Fee`, to estimate fee on declare v2 based on the contract version
-   Removes unused variable
-  Closes 
- #353 
- #344
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/0xSpaceShard/starknet-hardhat-example):https://github.com/0xSpaceShard/starknet-hardhat-example/pull/110
- …

Support estimate fee on declare v2

---

src/adapt.ts

- Support the recently introduced EthAddress type
- Partly address #341 
- Format the code with `npm run format`
-   [ ] Restored `test.sh` to to use the …

Support eth address

---

src/types/index.ts

Allow constructor-less contracts
-   Fixes `TypeError: Cannot read properties of undefined (reading 'selector')` when getting contract factory with no constructor.
-   NA
-   [ ] Modified `test.sh` to use my …

Fix bug: allow constructorless contracts

---

src/devnet-utils.ts
src/types/devnet.ts

-   `payload` type changed from `number` to `Numeric` for `consumeMessageFromL2` devnet function
-   NA
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

Fix payload type

---

src/types/index.ts

-   N/A
-  closes #367  Refactor of the resolveConstructorPredicate() function. If the CONSTRUCTOR property is not declared in .casm, or if the value is an empty array, it will no longer produce an error. Instead, the function will immediately return a boolean false.
-   [X] Formatted the code
-   [X] No linter errors + tried to avoid introducing linter warnings
-   [X] Performed a self-review of the code
-   [X] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/0xSpaceShard/sta …

Refactor constructor checking

---

scripts/test-setup.sh
src/adapt.ts

- Closes #356
-   `adaptInputUtil` return type changed `StringMap` ->  `unknown`
-   NA
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/0xSpaceShard/starknet-hardhat-example):https://github.com/0xSpaceShard/starknet-hardhat-example/pull/111
-   [ ] Restored `test.sh` to to …

Update adaptInputUtil function return type

---

config.json
scripts/setup-cairo1-compiler.sh
scripts/setup-config-test-dependencies.sh
scripts/test-dev.sh
scripts/test.sh

- Close #363
- Default to cairo-lang 0.11.1.1 in dockerized mode
- Partly address #369
- Using cairo v1.0.0-rc0
- Not supporting imports
- Not supporting config (toml) file
- Use devnet v0.5.2 (for testing and integrated-devnet)
- Apply formatting in some bash files
- In setup-cairo1-compiler.sh, read compiler version from config.json
- Rename `scripts/setup-cairo1-compiler.sh` to `scripts/setup-config-test-dependencies.sh`
-   [x] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, …

Adapt to cairo-lang/starknet 0.11.1

---

scripts/test-setup.sh
test/general-tests/cairo0-constructor-test/check.ts
test/general-tests/cairo0-constructor-test/hardhat.config.ts
test/general-tests/cairo0-constructor-test/network.json
test/general-tests/constructor-test/check.ts
test/general-tests/constructor-test/commented_constructor.cairo
test/general-tests/constructor-test/duplicate_constructor.cairo
test/general-tests/constructor-test/empty_line_constructor.cairo
test/general-tests/constructor-test/mute_constructor.cairo
test/general-tests/constructor-test/no_constructor.cairo

-   NA
-   Closes #350 
-   Introduces new test coverage for constructor chcker
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/0xSpaceShard/starknet-hardhat-example):https://github.com/0xSpaceShard/starknet-hardhat-example/pull/113
-   [x] Restored `test.sh` to to use the …

Add tests for constructor checker

---

package-lock.json
package.json
src/account-utils.ts
src/account.ts
src/adapt.ts
src/devnet-utils.ts
src/extend-utils.ts
src/index.ts
src/starknet-js-wrapper.ts
src/starknet-types.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/type-extensions.ts
src/types/index.ts
src/types/starknet.ts
src/utils.ts
tsconfig.json
www/docs/dev.md

- For happiest path scenarios the hope is that users should not be affected
- Minor API changes for ancillary functionalities and functions, most notably a truncated response for the `getBlock` method
- Some internally re-thrown errors might be different due to differences in the underlying tool used
- Starknet CLI internal usage removal in favour of starknet.js (`~5.17.0`) utilization
- new `starknetJs` property available for the runtime environment
- Resolves: #395 
- Resolves: #140 
-   [ ] Updated the `test` directory (with a test …

Replace internal Starknet CLI usage with starknet.js

---

src/external-server/create-devnet-wrapper.ts
src/utils.ts
test/integrated-devnet-tests/with-docker-full-image/check.ts
test/integrated-devnet-tests/with-docker-full-image/hardhat.config.ts
test/integrated-devnet-tests/with-docker-full-image/network.json
www/docs/intro.md

Support full image specification of dockerized integrated-devnet
