README.md
package.json
scripts/test.sh
src/index.ts
src/types.ts
src/utils.ts

- Improve testing documentation.
- Add config check in testing script.
- Fix url network check.
- Refactor logging (create a `utils` file for this).
- Bump version.

Bug fix, logging improvement, documentation addition

---

README.md
package-lock.json
package.json
scripts/npm-publish.sh
src/adapt.ts
src/index.ts
src/type-extensions.ts
src/types.ts
test/with-deploy-inputs/check.sh
test/with-deploy-inputs/hardhat.config.ts

- Enable passing constructor arguments with `starknet-deploy` task (`--inputs`).
- Fix typos in docs.
- Improve error messages.
- Improve typing of the object holding `invoke`/`call`/`deploy` arguments.
- Improve typing in adapt functions (`StringMap` - object with string keys).
- Refactor gateway_url extraction.
- Update packages.
- Use more descriptive names in publish script.

Upgrade to v0.3.2

---

src/starknet-wrappers.ts
test/configuration-tests/with-wait/check.sh
test/general-tests/starknet-verify/check.sh

Fixed dockerOptions, changed tests to not use test.cairo file

Fixed dockerOptions, changed tests to not use test.cairo file

---

.eslintrc.json
README.md
package-lock.json
src/constants.ts
src/extend-utils.ts
src/index.ts
src/starknet-wrappers.ts
src/task-actions.ts
src/type-extensions.ts
src/types.ts
src/utils.ts
test/configuration-tests/with-networks/check.sh
test/configuration-tests/with-networks/hardhat.config.ts
test/configuration-tests/with-networks/invalid-mocha-network.txt
test/configuration-tests/with-networks/invalid-starknet-network.txt
test/configuration-tests/with-networks/without-starknet-network.txt

Log available networks

---

.circleci/config.yml
README.md
package-lock.json
package.json
src/adapt.ts
src/constants.ts
src/task-actions.ts
test/configuration-tests/with-cairo-version/hardhat.config.ts
test/general-tests/open-zeppelin-cairo-contracts/hardhat.config.ts

Updated to cairo-lang 0.7.0:
- Allow input and output of array structs
Negative value outputs are now properly parsed,

Accept arrays of structs as inputs and outputs

---

src/constants.ts
test/general-tests/wallet-test/hardhat.config.ts

-Increased timeout on tx status check
-Added wallet to config file

Fix account support

---

.circleci/config.yml
src/constants.ts
test/configuration-tests/with-cairo-version/hardhat.config.ts
test/general-tests/open-zeppelin-cairo-contracts/hardhat.config.ts

Update to cairo version 0.7.1
Readme will be updated when updating the semver and creating the release tag

Updated to cairo 0.7.1

---

package-lock.json
package.json
scripts/test.sh
test/configuration-tests/with-networks/check.sh
test/general-tests/function-argument-number/check.sh
test/general-tests/getContractFactory/check.sh
test/general-tests/plain/check.sh
test/general-tests/short-string-test/check.sh
test/general-tests/transaction-signing/check.sh
test/general-tests/wallet-test/check.sh
test/venv-tests/with-venv/check.sh

Moved `hardhat` to `peerDependencies`

Move hardhat to peerDependencies

---

package-lock.json
package.json
scripts/install-devnet.sh

- Bump version to v0.5.3
- Update hardhat to v2.9.3
- Update versions of dependencies reporting critical issues.
- Install devnet from pypi instead of github (v0.1.21)
Most of the things from the TODO list were not needed as there were no changes to the source code.

Release v0.5.3

---

src/account.ts
src/types.ts
test/general-tests/account-test/network.json

- Added `transactionVersion` to `FeeEstimateOptions`
- Skipped `account` tests on devnet

Fix fee estimate

---

.circleci/config.yml
scripts/get-version.py
scripts/install-devnet.sh
scripts/versions.sh

None
- So far devnet installation and caching were not synchronised (installation was using some fixed version from pypi, caching was checking the latest github commit of the devnet repo). This is now fixed.

Fix Devnet caching

---

config.json
package-lock.json
package.json
src/constants.ts
src/extend-utils.ts
src/starknet-types.ts
src/starknet-wrappers.ts
src/type-extensions.ts
src/types.ts
src/utils.ts

- Adapt to cairo-lang 0.8.2
- Default to the latest block in getBlock
- Update to devnet 0.2.1
- Introduce type BlockNumber that can be `number`, `"pending"`, or `"latest"`
TODO:
- Should defaulting to `pending` be replaced with defaulting to `latest`?
- Where else is defaulting not implemented?

Cairo lang 0.8.2

---

test/general-tests/devnet-block-time/check.sh
test/general-tests/devnet-block-time/hardhat.config.ts
test/general-tests/devnet-block-time/network.json

- 
- Added test for executing `devnet-block-time.ts` in example repo.

Add time manipulation test

---

src/task-actions.ts
src/type-extensions.ts

- Removed unused argument in `getContractFactory`
-

Removed unused argument

---

README.md
src/devnet/create-devnet-wrapper.ts
src/index.ts
src/utils.ts

-  For `arm` machines `-arm` image will be pulled. On images `integrated-devnet` and `cairo-cli`.
-

Arm docker image

---

src/devnet/integrated-devnet.ts

- Prevent connection errors from happening on integrated-devnet startup (if sleeping for a too short period of time)
None

Use sleep-check loop on integrated-devnet startup

---

README.md

-   None
- None
-   [ ] Formatted the code
-   [ ] No linter errors
-   [ ] Tried to avoid introducing linter warnings
-   [ ] Performed a self-review of the code
-   [ ] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Updated the `test` directory
-   [ ] All tests are passing

Minor fix to Readme

---

README.md
src/index.ts
src/task-actions.ts
test/general-tests/starknet-plugin-version/check.sh
test/general-tests/starknet-plugin-version/hardhat.config.ts
test/general-tests/starknet-plugin-version/network.json

-  Plugin version can be printed using task `npx hardhat starknet-plugin-version`
-  Closes #163 
-   NA
-   [ ] Restored `test.sh` to to use the original …

Starknet plugin version

---

src/devnet/external-server.ts
src/devnet/integrated-devnet-logger.ts

- Rewrite old log file instead of appending to it
- Refactor integrated-devnet logging of last error

Improve integrated devnet logging

---

package-lock.json
package.json

-   Introduces a [tool](https://github.com/prettier/prettier-eslint-cli) that handles a conflict that occurs when using `prettier` and `eslint` separately.
-   Closes #194 
-   Removed `prettier` from dependencies which was used for formatting.
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`) …

Add linter and formatter tool prettier-eslint-cli 

---

README.md
scripts/test.sh
src/devnet-utils.ts
src/type-extensions.ts
test/general-tests/devnet-create-block/check.sh
test/general-tests/devnet-create-block/hardhat.config.ts
test/general-tests/devnet-create-block/network.json

- Supersedes #186 
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
-   https://github.com/Shard-Labs/starknet-hardhat-example/pull/77
-   [x] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
- …

Add createBlock wrapper

---

.github/pull_request_template.md
README.md

Docs change, no impact on users
This way, the documentation will stay true even if the line referenced changes in the future commits

[chore] Update API link in README.md

---

README-dev.md
scripts/npm-publish.sh

- Update release notes in `README-dev.md`

Update release notes [skip ci]

---

README.md
src/index.ts
src/starknet-wrappers.ts
src/starknet_cli_wrapper.py
src/task-actions.ts
test/general-tests/cairo-migrate/check.sh
test/general-tests/cairo-migrate/hardhat.config.ts
test/general-tests/cairo-migrate/network.json
test/general-tests/cairo-migrate/old_contract.cairo

-  Implements `cairo-migrate` option to convert old Cairo contracts to use new syntax
-  Closes #216 
-  NA
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

Support cairo-migrate

---

README.md
package-lock.json
package.json
src/utils.ts

-   Fix for WSL docker integration problems in `integrated-devnet` network mode
-   Remove of `is-wsl` dependency.
-   [x] If `src/type-extensions.ts` was changed, updated the line number referencing this file in the `## API` section of README.md

isWsl fix for WSL

---

README.md
src/task-actions.ts
test/configuration-tests/with-cli-network/check.sh
test/general-tests/hardhat-run/check.sh

- Basically repeat what we did in #74 
- Close #226 (it make sense to close this but then we need to open a new issue)
- Disable corresponding test

Throw if --starknet-network provided with hh run

---

src/index.ts
src/task-actions.ts
src/utils.ts
test/configuration-tests/with-cairo-path/hardhat.config.ts
www/docs/intro.md

Refactor path adaptation

---

scripts/test.sh
src/account.ts
src/types/index.ts

-   Closes #315 
-   NA
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):https://github.com/Shard-Labs/starknet-hardhat-example/pull/100 …

Provide nonce on deploy function

---

src/constants.ts
src/external-server/docker-server.ts
src/external-server/external-server.ts
src/starknet-docker-proxy.ts
src/starknet-wrappers.ts
src/utils.ts

- Close #321 
-   [ ] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] All tests are passing (for external …

Docker Desktop support

---

package-lock.json
package.json
scripts/test-setup.sh
src/account-utils.ts
src/account.ts
src/devnet-utils.ts
src/extend-utils.ts
src/external-server/external-server.ts
src/starknet-types.ts
src/starknet-wrappers.ts
src/utils.ts
test/configuration-tests/with-request-timeout-1ms/check.ts

- updates starknet.js and other dependencies
- removes the `handleJsonWithBigInt` utility method
-  
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
-   https://github.com/0xSpaceShard/starknet-hardhat-example/pull/108
-   [x] Restored …

Bump starknet.js dependency

---

src/account.ts
src/adapt.ts
src/extend-utils.ts
src/index.ts
src/recompiler.ts
src/task-actions.ts
src/types/devnet.ts
src/types/index.ts
src/types/starknet.ts
www/docs/dev.md
www/docs/intro.md

-   Closes #382
-   Fixes typos in comments and varibales
-   NA.

Spelling fix

---

scripts/test-setup.sh
test/general-tests/declare-v2-test/check.ts
test/general-tests/decode-event-v2-test/check.ts
test/general-tests/decode-event-v2-test/hardhat.config.ts
test/general-tests/decode-event-v2-test/network.json
www/docs/dev.md

Fix #378 
- updated declare-v2-test path to match starknet-hardhat-example directory test/cairo1
- add doc for "Executing individual tests with dockerized environnement"
Corresponding example-repo PR: https://github.com/0xSpaceShard/starknet-hardhat-example/pull/114

Cairo1 events

---

scripts/test.sh

-   Closes #391
-   Validates config file on test

Validate config file on test
